
## Ara SOC
set_property -dict {PACKAGE_PIN BE41 IOSTANDARD LVCMOS18} [get_ports exit_o[63]]
set_property -dict {PACKAGE_PIN BD41 IOSTANDARD LVCMOS18} [get_ports exit_o[62]]
set_property -dict {PACKAGE_PIN BF46 IOSTANDARD LVCMOS18} [get_ports exit_o[61]]
set_property -dict {PACKAGE_PIN BF45 IOSTANDARD LVCMOS18} [get_ports exit_o[60]]
set_property -dict {PACKAGE_PIN BF43 IOSTANDARD LVCMOS18} [get_ports exit_o[59]]
set_property -dict {PACKAGE_PIN BF42 IOSTANDARD LVCMOS18} [get_ports exit_o[58]]
set_property -dict {PACKAGE_PIN BE46 IOSTANDARD LVCMOS18} [get_ports exit_o[57]]
set_property -dict {PACKAGE_PIN BE45 IOSTANDARD LVCMOS18} [get_ports exit_o[56]]
set_property -dict {PACKAGE_PIN BD42 IOSTANDARD LVCMOS18} [get_ports exit_o[55]]
set_property -dict {PACKAGE_PIN BC42 IOSTANDARD LVCMOS18} [get_ports exit_o[54]]
set_property -dict {PACKAGE_PIN BE44 IOSTANDARD LVCMOS18} [get_ports exit_o[53]]
set_property -dict {PACKAGE_PIN BE43 IOSTANDARD LVCMOS18} [get_ports exit_o[52]]
set_property -dict {PACKAGE_PIN BL50 IOSTANDARD LVCMOS18} [get_ports exit_o[51]]
set_property -dict {PACKAGE_PIN BL48 IOSTANDARD LVCMOS18} [get_ports exit_o[50]]
set_property -dict {PACKAGE_PIN BF53 IOSTANDARD LVCMOS18} [get_ports exit_o[49]]
set_property -dict {PACKAGE_PIN BG47 IOSTANDARD LVCMOS18} [get_ports exit_o[48]]
set_property -dict {PACKAGE_PIN BP49 IOSTANDARD LVCMOS18} [get_ports exit_o[47]]
set_property -dict {PACKAGE_PIN BP48 IOSTANDARD LVCMOS18} [get_ports exit_o[46]]
set_property -dict {PACKAGE_PIN BN51 IOSTANDARD LVCMOS18} [get_ports exit_o[45]]
set_property -dict {PACKAGE_PIN BN50 IOSTANDARD LVCMOS18} [get_ports exit_o[44]]
set_property -dict {PACKAGE_PIN BN49 IOSTANDARD LVCMOS18} [get_ports exit_o[43]]
set_property -dict {PACKAGE_PIN BM48 IOSTANDARD LVCMOS18} [get_ports exit_o[42]]
set_property -dict {PACKAGE_PIN BM50 IOSTANDARD LVCMOS18} [get_ports exit_o[41]]
set_property -dict {PACKAGE_PIN BM49 IOSTANDARD LVCMOS18} [get_ports exit_o[40]]
set_property -dict {PACKAGE_PIN BM52 IOSTANDARD LVCMOS18} [get_ports exit_o[39]]
set_property -dict {PACKAGE_PIN BL51 IOSTANDARD LVCMOS18} [get_ports exit_o[38]]
set_property -dict {PACKAGE_PIN BL53 IOSTANDARD LVCMOS18} [get_ports exit_o[37]]
set_property -dict {PACKAGE_PIN BL52 IOSTANDARD LVCMOS18} [get_ports exit_o[36]]
set_property -dict {PACKAGE_PIN BK49 IOSTANDARD LVCMOS18} [get_ports exit_o[35]]
set_property -dict {PACKAGE_PIN BK48 IOSTANDARD LVCMOS18} [get_ports exit_o[34]]
set_property -dict {PACKAGE_PIN BK51 IOSTANDARD LVCMOS18} [get_ports exit_o[33]]
set_property -dict {PACKAGE_PIN BK50 IOSTANDARD LVCMOS18} [get_ports exit_o[32]]
set_property -dict {PACKAGE_PIN BJ49 IOSTANDARD LVCMOS18} [get_ports exit_o[31]]
set_property -dict {PACKAGE_PIN BJ48 IOSTANDARD LVCMOS18} [get_ports exit_o[30]]
set_property -dict {PACKAGE_PIN BJ47 IOSTANDARD LVCMOS18} [get_ports exit_o[29]]
set_property -dict {PACKAGE_PIN BH47 IOSTANDARD LVCMOS18} [get_ports exit_o[28]]
set_property -dict {PACKAGE_PIN BJ51 IOSTANDARD LVCMOS18} [get_ports exit_o[27]]
set_property -dict {PACKAGE_PIN BH51 IOSTANDARD LVCMOS18} [get_ports exit_o[26]]
set_property -dict {PACKAGE_PIN BH50 IOSTANDARD LVCMOS18} [get_ports exit_o[25]]
set_property -dict {PACKAGE_PIN BH49 IOSTANDARD LVCMOS18} [get_ports exit_o[24]]
set_property -dict {PACKAGE_PIN BJ53 IOSTANDARD LVCMOS18} [get_ports exit_o[23]]
set_property -dict {PACKAGE_PIN BJ52 IOSTANDARD LVCMOS18} [get_ports exit_o[22]]
set_property -dict {PACKAGE_PIN BH52 IOSTANDARD LVCMOS18} [get_ports exit_o[21]]
set_property -dict {PACKAGE_PIN BG52 IOSTANDARD LVCMOS18} [get_ports exit_o[20]]
set_property -dict {PACKAGE_PIN BK54 IOSTANDARD LVCMOS18} [get_ports exit_o[19]]
set_property -dict {PACKAGE_PIN BK53 IOSTANDARD LVCMOS18} [get_ports exit_o[18]]
set_property -dict {PACKAGE_PIN BJ54 IOSTANDARD LVCMOS18} [get_ports exit_o[17]]
set_property -dict {PACKAGE_PIN BH54 IOSTANDARD LVCMOS18} [get_ports exit_o[16]]
set_property -dict {PACKAGE_PIN BG54 IOSTANDARD LVCMOS18} [get_ports exit_o[15]]
set_property -dict {PACKAGE_PIN BG53 IOSTANDARD LVCMOS18} [get_ports exit_o[14]]
set_property -dict {PACKAGE_PIN BE54 IOSTANDARD LVCMOS18} [get_ports exit_o[13]]
set_property -dict {PACKAGE_PIN BE53 IOSTANDARD LVCMOS18} [get_ports exit_o[12]]
set_property -dict {PACKAGE_PIN BG49 IOSTANDARD LVCMOS18} [get_ports exit_o[11]]
set_property -dict {PACKAGE_PIN BG48 IOSTANDARD LVCMOS18} [get_ports exit_o[10]]
set_property -dict {PACKAGE_PIN BG50 IOSTANDARD LVCMOS18} [get_ports exit_o[9]]
set_property -dict {PACKAGE_PIN BF50 IOSTANDARD LVCMOS18} [get_ports exit_o[8]]
set_property -dict {PACKAGE_PIN BF52 IOSTANDARD LVCMOS18} [get_ports exit_o[7]]
set_property -dict {PACKAGE_PIN BF51 IOSTANDARD LVCMOS18} [get_ports exit_o[6]]
set_property -dict {PACKAGE_PIN BF48 IOSTANDARD LVCMOS18} [get_ports exit_o[5]]
set_property -dict {PACKAGE_PIN BF47 IOSTANDARD LVCMOS18} [get_ports exit_o[4]]
set_property -dict {PACKAGE_PIN BE50 IOSTANDARD LVCMOS18} [get_ports exit_o[3]]
set_property -dict {PACKAGE_PIN BE49 IOSTANDARD LVCMOS18} [get_ports exit_o[2]]
set_property -dict {PACKAGE_PIN BE51 IOSTANDARD LVCMOS18} [get_ports exit_o[1]]
set_property -dict {PACKAGE_PIN BD51 IOSTANDARD LVCMOS18} [get_ports exit_o[0]]

## CLK
set_property -dict {PACKAGE_PIN BJ24 IOSTANDARD LVCMOS18} [get_ports clk_i]

## RESET
set_property -dict {PACKAGE_PIN BH26 IOSTANDARD LVCMOS18} [get_ports rst_ni]

## UART
set_property -dict {PACKAGE_PIN BF21 IOSTANDARD LVCMOS18} [get_ports rx_i]
set_property -dict {PACKAGE_PIN BF22 IOSTANDARD LVCMOS18} [get_ports tx_o]

#set_property -dict {PACKAGE_PIN A28 IOSTANDARD LVCMOS18} [get_ports tx_o]
#set_property -dict {PACKAGE_PIN B33 IOSTANDARD LVCMOS18} [get_ports rx_i]


