// Copyright 2024 ETH Zurich and University of Bologna.
//
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <stdint.h>

#include "kernel/aes.h"
#include "runtime.h"

#ifdef SPIKE
#include <stdio.h>
#else
#include "printf.h"
#endif

// Provided by data.S (generated by script/gen_data.py):
//   N            : number of 16-byte blocks
//   round_keys   : 11 × 128-bit AES-128 round keys, packed as 44 u32 words
//   plaintext    : N × 16 bytes of input data
//   ciphertext_g : N × 16 bytes of reference AES-128 ECB ciphertext
extern const uint64_t N;
extern const uint32_t round_keys[] __attribute__((aligned(16)));
extern const uint32_t plaintext[] __attribute__((aligned(4 * NR_LANES)));
extern const uint32_t ciphertext_g[] __attribute__((aligned(4 * NR_LANES)));
extern uint32_t ciphertext[] __attribute__((aligned(4 * NR_LANES)));
extern uint32_t roundtrip[] __attribute__((aligned(4 * NR_LANES)));

int main() {
  printf("\n");
  printf("=========\n");
  printf("=  AES  =\n");
  printf("=========\n");
  printf("\n");
  printf("Running AES-128 ECB on %lu blocks (%lu bytes).\n", (unsigned long)N,
         (unsigned long)(N * AES_BLOCK_BYTES));

  // Encrypt
  start_timer();
  aes128_ecb_encrypt_vec(round_keys, plaintext, ciphertext, N);
  stop_timer();
  int64_t enc_runtime = get_timer();

  // Decrypt the ciphertext we just produced
  start_timer();
  aes128_ecb_decrypt_vec(round_keys, ciphertext, roundtrip, N);
  stop_timer();
  int64_t dec_runtime = get_timer();

  size_t bytes = N * AES_BLOCK_BYTES;
  printf("Encrypt: %ld cycles (%lu bytes, %f B/cycle)\n", enc_runtime,
         (unsigned long)bytes, (float)bytes / (float)enc_runtime);
  printf("Decrypt: %ld cycles (%lu bytes, %f B/cycle)\n", dec_runtime,
         (unsigned long)bytes, (float)bytes / (float)dec_runtime);

  // Verify encryption against the reference ciphertext.
  for (uint64_t i = 0; i < N * AES_BLOCK_WORDS; ++i) {
    if (ciphertext[i] != ciphertext_g[i]) {
      printf("Encrypt error at word %lu: 0x%08x != 0x%08x\n", (unsigned long)i,
             ciphertext[i], ciphertext_g[i]);
      return 1;
    }
  }
  // Verify decryption round-trips back to the plaintext.
  for (uint64_t i = 0; i < N * AES_BLOCK_WORDS; ++i) {
    if (roundtrip[i] != plaintext[i]) {
      printf("Decrypt error at word %lu: 0x%08x != 0x%08x\n", (unsigned long)i,
             roundtrip[i], plaintext[i]);
      return 2;
    }
  }
  printf("Passed.\n");
  return 0;
}
