
-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/tech_cells_generic/src/rtl/tc_sram.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/tech_cells_generic/src/rtl/tc_sram_impl.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/tech_cells_generic/src/rtl/tc_clk.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/tech_cells_generic/src/deprecated/pulp_clock_gating_async.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/tech_cells_generic/src/deprecated/cluster_clk_cells.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/tech_cells_generic/src/deprecated/pulp_clk_cells.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/binary_to_gray.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cb_filter_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cc_onehot.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cdc_reset_ctrlr_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cf_math_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/clk_int_div.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/credit_counter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/delta_counter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/ecc_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/edge_propagator_tx.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/exp_backoff.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/fifo_v3.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/gray_to_binary.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/isochronous_4phase_handshake.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/isochronous_spill_register.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/lfsr.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/lfsr_16bit.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/lfsr_8bit.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/lossy_valid_to_stream.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/mv_filter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/onehot_to_bin.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/plru_tree.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/passthrough_stream_fifo.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/popcount.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/rr_arb_tree.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/rstgen_bypass.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/serial_deglitch.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/shift_reg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/shift_reg_gated.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/spill_register_flushable.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_demux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_filter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_fork.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_intf.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_join_dynamic.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_mux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_throttle.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/sub_per_hash.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/sync.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/sync_wedge.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/unread.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/read.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/addr_decode_dync.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cdc_2phase.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cdc_4phase.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/clk_int_div_static.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/addr_decode.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/addr_decode_napot.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/multiaddr_decode.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cb_filter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cdc_fifo_2phase.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/clk_mux_glitch_free.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/counter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/ecc_decode.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/ecc_encode.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/edge_detect.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/lzc.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/max_counter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/rstgen.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/spill_register.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_delay.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_fifo.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_fork_dynamic.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_join.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cdc_reset_ctrlr.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cdc_fifo_gray.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/fall_through_register.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/id_queue.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_to_mem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_arbiter_flushable.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_fifo_optimal_wrap.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_register.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_xbar.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cdc_fifo_gray_clearable.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/cdc_2phase_clearable.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/mem_to_banks_detailed.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_arbiter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/stream_omega_net.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/mem_to_banks.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/clock_divider_counter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/clk_div.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/find_first_one.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/generic_LFSR_8bit.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/generic_fifo.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/prioarbiter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/pulp_sync.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/pulp_sync_wedge.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/rrarbiter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/clock_divider.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/fifo_v2.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/deprecated/fifo_v1.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/edge_propagator_ack.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/edge_propagator.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/src/edge_propagator_rx.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpu_div_sqrt_mvp/hdl/control_mvp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpu_div_sqrt_mvp/hdl/div_sqrt_mvp_wrapper.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_intf.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_atop_filter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_burst_splitter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_bus_compare.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_cdc_dst.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_cdc_src.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_cut.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_delayer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_demux_simple.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_dw_downsizer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_dw_upsizer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_fifo.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_id_remap.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_id_prepend.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_isolate.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_join.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_demux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_dw_converter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_from_mem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_join.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_lfsr.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_mailbox.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_mux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_regs.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_to_apb.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_to_axi.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_modify_address.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_mux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_rw_join.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_rw_split.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_serializer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_slave_compare.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_throttle.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_to_detailed_mem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_cdc.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_demux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_err_slv.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_dw_converter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_from_mem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_id_serialize.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lfsr.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_multicut.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_to_axi_lite.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_to_mem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_zero_mem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_interleaved_xbar.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_iw_converter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_lite_xbar.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_xbar_unmuxed.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_to_mem_banked.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_to_mem_interleaved.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_to_mem_split.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_xbar.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/src/axi_xp.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_cast_multi.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_classifier.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_divsqrt_th_32.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_divsqrt_th_64_multi.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_divsqrt_multi.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_fma.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_fma_multi.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_sdotp_multi.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_sdotp_multi_wrapper.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_noncomp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_opgroup_block.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_opgroup_fmt_slice.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_opgroup_multifmt_slice.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_rounding.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/lfsr_sr.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/fpnew/src/fpnew_top.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/apb/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/apb/src/apb_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/apb/src/apb_intf.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/apb/src/apb_err_slv.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/apb/src/apb_regs.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/apb/src/apb_cdc.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/apb/src/apb_demux.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/common/local/util
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include/config_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include/riscv_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include/ariane_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include/build_config_pkg.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/common/local/util
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cva6_accel_first_pass_decoder_stub.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/common/local/util
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include/wt_cache_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include/std_cache_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cvxif_example/include/cvxif_instr_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cvxif_fu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cvxif_issue_register_commit_if_driver.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cvxif_compressed_if_driver.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cvxif_example/cvxif_example_coprocessor.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cvxif_example/instr_decoder.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cva6_rvfi_probes.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cva6_fifo_v3.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cva6.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/alu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/fpu_wrap.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/branch_unit.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/compressed_decoder.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/controller.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/csr_buffer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/csr_regfile.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/decoder.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/ex_stage.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/acc_dispatcher.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/instr_realign.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/macro_decoder.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/id_stage.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/issue_read_operands.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/issue_stage.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/load_unit.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/load_store_unit.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/lsu_bypass.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/mult.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/multiplier.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/serdiv.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/perf_counters.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/ariane_regfile_ff.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/ariane_regfile_fpga.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/scoreboard.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/store_buffer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/amo_buffer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/store_unit.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/commit_stage.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/axi_shim.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/frontend/btb.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/frontend/bht.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/frontend/ras.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/frontend/instr_scan.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/frontend/instr_queue.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/frontend/frontend.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/wt_dcache_ctrl.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/wt_dcache_mem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/wt_dcache_missunit.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/wt_dcache.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/wt_cache_subsystem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/wt_axi_adapter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/cva6_icache.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/tag_cmp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/cache_ctrl.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/amo_alu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/axi_adapter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/miss_handler.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/std_nbdcache.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/std_cache_subsystem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg_initialized.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/cva6_hpdcache_subsystem.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/cva6_hpdcache_wrapper.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache_tc_sram.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/pmp/src/pmp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/pmp/src/pmp_entry.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/pmp/src/pmp_data_if.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/vendor/pulp-platform/fpga-support/fpga-support-stubs.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/common/local/util/tc_sram_wrapper.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/common/local/util/tc_sram_wrapper_cache_techno.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/common/local/util/sram_pulp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/common/local/util/sram_cache.sv

-DTARGET_SYNTHESIS
-DTARGET_VERILATOR
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/apb/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/axi/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/common_cells/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/cache_subsystem/hpdcache/rtl/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/deps/cva6/core/include
-I/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/include
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/include/rvv_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/include/ara_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/include/pf_pkg.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/segment_sequencer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/ctrl_registers.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/cva6_accel_first_pass_decoder.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/ara_dispatcher.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/ara_sequencer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/axi_inval_filter.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/lane_sequencer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/operand_queue.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/operand_requester.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/simd_alu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/simd_div.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/simd_mul.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/vector_regfile.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/power_gating_generic.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/masku/masku_operands.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/sldu/p2_stride_gen.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/sldu/sldu_op_dp.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/sldu/sldu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/addrgen.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/vldu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/vstu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/pf_classifier.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/pf_predictor.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/pf_data_buffer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/pf_r_router.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/pf_rob.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/prefetch_buffer.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/operand_queues_stage.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/valu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/vmfpu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/fixed_p_rounding.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/vlsu/vlsu.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/masku/masku.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/vector_fus_stage.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/lane/lane.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/ara.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/ara_system.sv
/Users/catherineye/Library/CloudStorage/OneDrive-UniversityofWaterloo/uw/ra/ECE499/WORKSPACE/ara/hardware/src/ara_soc.sv

